### ISSUE TITLE
Migrate cing to github

### ISSUE THREAD

**Issue by GoogleCodeExporter** [VuisterLab/cing#348]
```
The cing google code projects needs to be migrated to github before August 24, 
2015 - the site then goes read-only 
(http://google-opensource.blogspot.nl/2015/03/farewell-to-google-code.html).

We add it to an existing repo from Geerten's lab, set up a new organisation for 
Geerten's lab or NMR_REDO specifically, or add it to the CMBI organisation 
(https://github.com/cmbi - note that many projects and people are hidden) if 
that's convenient.
```

Original issue reported on code.google.com by `WGTouw` on 17 Apr 2015 at 7:04

**Comment by tjragan** [comment]
I'm transferring the project to github in the VuisterLab repo.

While I'm at it, I think we should switch to a [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) style repo.
This will involve renaming **master** to **develop**, and allowing Geerten to continue working on V2 there.  I'll then move the stable branch (the one that we're currently using for production,) to **master**, clean it up a bit, and tag it with V1.0.

**Comment by tjragan** [comment]
Ok, after talking with Geerten, I'll finish converting the branch to the git-flow style.  
I'm also going to update the issue links from google code to github.
Apply the changes I've made to master.
Tag the V1.0 / CASD-NMR-2013 release(s).
